---
name: "Acceptance Test"
on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - "dev/trigger-ci"
jobs:
  test:
    name: "Test ${{ matrix.tag }} on ${{ matrix.browser }}"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "black-box"
        browser:
          - "Firefox"
          - "Chrome"
        exclude:
          - tag: "black-box"
            browser: Firefox
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
        with:
          submodules: true
      - name: "Create external volumes"
        run: |
          make -C hack/ create-volumes
      - name: "Start MySQL"
        run: |
          docker compose up -d mysql
        working-directory: ./hack
      - name: "Build images"
        run: |
          make -C hack/ build
        env:
          PYTHON_VERSION: "3.9"
      - name: "Start services"
        run: |
          docker compose up -d
        env:
          ELASTICSEARCH_DISK_THRESHOLD_ENABLED: "false"
        working-directory: ./hack
      - name: "Bootstrap services"
        run: |
          make -C hack/ bootstrap
      - name: "Restart services"
        run: |
          make -C hack/ restart-am-services
      - name: "Run AMAUAT tag"
        run: |
          make -C hack/ test-at-behave TAGS="${{ matrix.tag }}" BROWSER=${{ matrix.browser }}
      - name: "Show logs"
        if: ${{ !cancelled() }}
        run: |
          docker compose logs archivematica-mcp-server
          docker compose logs archivematica-mcp-client
          docker compose logs archivematica-dashboard
          docker compose logs archivematica-storage-service
        working-directory: ./hack
